### ISSUE TITLE
Add draggability/reordering of UTubs

### ISSUE THREAD

**Issue by rehankalu** [4IRL/urls4irl#21]
User should be able to rearrange (drag-drop), date-of-creation sort, or alphasort UTubs

**Comment by GPropersi** [comment]
I think we can do date-of-creation, or alphasort, or by last updated on the client side - but manual rearranging would prove cumbersome, as the order of UTubs would have to be unique to each user. We could some hacking client side but would be cumbersome than beneficial I think.

Consider two users being in one UTub but otherwise vastly different UTubs. If first user chooses that UTub to be first, and second user doesn't, how should we handle that?
